---
# tasks file for ansible-role-laniakea-rstudio-express-config

- name: Change RStudio user password
  import_tasks: change_password.yml

- name: Start rstudio-server
  systemd:
    state: started
    enabled: yes
    name: rstudio-server.service
  become: yes

- name: Wait RStudio
  wait_for:
    host: 127.0.0.1
    port: '8080'
    timeout: 300
